{% set PKG_NAME = 'teensy-minimal-rpc' %}
{% set LIB_NAME = 'TeensyMinimalRpc' %}
{% set MODULE_NAME = PKG_NAME.replace('-', '_') %}

{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}

# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

#: .. versionadded:: 0.7
build:
  #: .. versionadded:: 0.8
  noarch: python
  script:
    # Generate Arduino `library.properties` file
    - python -m paver generate_arduino_library_properties
    # Generate Arduino code
    - python -m paver generate_all_code
    # Copy Arduino library to Conda include directory
    - python -c
        "import os.path; import os; import shutil; import platformio_helpers as pioh;
        lib_src_dir = os.path.join(os.environ['SRC_DIR'], 'lib',
                                   '{{ LIB_NAME }}');
        install_dir = pioh.conda_arduino_include_path().joinpath('{{ LIB_NAME }}');
        shutil.copytree(lib_src_dir, install_dir);
        "
    # Generate `setup.py` from `pavement.py` definition.
    - python -m paver generate_setup
    # Install source directory as Python package.
    - python -B setup.py install --single-version-externally-managed --record record.txt

package:
  name: {{ PKG_NAME }}
  version: {{ GIT_VERSION }}

requirements:
  build:
    - base-node-rpc >=0.46
    #: .. versionadded:: 0.7
    - conda-helpers >=0.14
    - future
    - paver
    - pip
    #: .. versionchanged:: 0.7
    - python {{ python }}
    #: .. versionadded:: 0.7
    - six

# .. versionadded:: 0.8
#     Split into `noarch` C++ header package and platform-specific Python
#     package.
outputs:
  - name: {{ PKG_NAME }}-dev
    noarch: generic
    files:
      - share
  - name: {{ PKG_NAME }}
    noarch: python
    files:
      - Lib/site-packages/{{ MODULE_NAME }}
    requirements:
      run:
        - {{ pin_subpackage(PKG_NAME + '-dev', max_pin='x.x') }}
        - base-node-rpc >=0.46
        #: .. versionadded:: 0.7
        - conda-helpers >=0.14
        #: .. versionchanged:: 0.7
        - python {{ python }}
        #: .. versionadded:: 0.7
        - six
    test:
      imports:
        - teensy_minimal_rpc.ADC
        - teensy_minimal_rpc.DMA
        - teensy_minimal_rpc.PIT
        - teensy_minimal_rpc.SIM
        - teensy_minimal_rpc.adc_sampler
        - teensy_minimal_rpc.config
        - teensy_minimal_rpc.node
        - teensy_minimal_rpc.proxy
        - teensy_minimal_rpc.state

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  license: MIT
